backend/controllers/WithdrawalTypeController.php
<?php

namespace backend\controllers;

use common\controllers\BackEndController;
use common\models\WithdrawalTypeCountry;
use common\models\WithdrawalWallet;
use Yii;
use yii\data\ArrayDataProvider;
use yii\web\NotFoundHttpException;

/**
 * Class WithdrawalTypeController
 * @package backend\controllers
 */
class WithdrawalTypeController extends BackEndController
{
    /**
     * Lists all Job models.
     * @return mixed
     */
    public function actionIndex()
    {
        $types = WithdrawalWallet::getTypeLabels();
        $dataProvider = new ArrayDataProvider([
            'allModels' => array_map(function($type, $label) {
                $countries = WithdrawalTypeCountry::find()->joinWith(['country.translations'])->where(['type' => $type, 'locale' => 'ru-RU'])->select('mod_attribute_description.title')->column();
                return [
                    'type' => $type,
                    'label' => $label,
                    'countries' => implode(', ', $countries)
                ];
            }, array_keys($types), $types),
            'pagination' => [
                'pageSize' => 35,
            ],
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $type
     * @return bool|string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($type)
    {
        $types = WithdrawalWallet::getTypeLabels();
        if (!array_key_exists($type, $types)) {
            throw new NotFoundHttpException('Type not found');
        }
        if ($input = Yii::$app->request->post()) {
            $countries = Yii::$app->request->post('countries', '');
            $countries = !empty($countries) ? explode(',', $countries) : [];
            WithdrawalTypeCountry::deleteAll(['and',
                ['type' => $type],
                ['not', ['country_id' => $countries]]
            ]);
            foreach ($countries as $country_id) {
                WithdrawalTypeCountry::findOrCreate(['type' => $type, 'country_id' => $country_id]);
            }

            if (Yii::$app->request->isAjax) {
                return true;
            }
        }
        $countries = WithdrawalTypeCountry::find()
            ->select('mod_attribute_description.title')
            ->joinWith(['country.translations'])
            ->where(['type' => $type])
            ->andWhere(['locale' => 'ru-RU'])
            ->indexBy('country_id')
            ->column();
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('_form', [
                'type' => $type,
                'label' => $types[$type],
                'countries' => $countries,
                'isAjax' => true,
            ]);
        } else {
            return $this->render('_form', [
                'type' => $type,
                'label' => $types[$type],
                'countries' => $countries,
            ]);
        }
    }
}

backend/views/withdrawal-type/_form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var $type integer
 * @var $label string
 * @var $countries array
 */

?>

<?php $form = ActiveForm::begin([
    'options' => [
        'id' => 'withdrawal-type-form',
        'data-pjax' => false,
        'class' => 'ajax-submit',
    ],
]); ?>
    <?= Html::hiddenInput("type", $type) ?>
    <h2><?= $label?></h2>
    <div class="form-group selectize-input-container" style="margin-bottom: 50px;">
        <?= Html::label('Показывать в странах:', null, ['style' => 'margin: 0;'])?>
        <h6>(Если нужно показывать во всех странах - оставьте поле пустым)</h6>
        <?= Html::textarea("countries", null, ['id' => "countries-input"]) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('user', 'Update'), ['class' => 'btn btn-block btn-success', 'id' => 'submit-button']) ?>
    </div>

<?php ActiveForm::end(); ?>

<?php
$countryListUrl = Url::to(['/ajax/attribute-list', 'alias' => 'country']);
$options = json_encode(array_map(
    function($value, $title) {return ['id' => $value, 'value' => $title];},
    array_keys($countries), $countries
));
$values = json_encode(array_keys($countries));
$script = <<<JS
    $.pjax.defaults.timeout = 6000;
    
    $('#countries-input').selectize({
        options: $options,
        items: $values,
        valueField: 'id',
        labelField: 'value',
        searchField: ['value'],
        maxItems: null,
        plugins: ["remove_button"],
        persist: false,
        'load': function(query, callback) {
            if (!query.length)
                return callback();
            $.post('$countryListUrl', {
                    query: encodeURIComponent(query)
                },
                function(data) {
                    callback(data);
                }
            ).fail(function() {
                callback();
            });
        }
    });
JS;

$this->registerJs($script);

backend/views/withdrawal-type/index.php
<?php

use backend\assets\SelectizeAsset;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\JobSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

SelectizeAsset::register($this);
$this->title = 'Типы вывода денег';

?>
<div class="job-index">
    <div class="box box-danger">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        </div>
        <div class="box-body">
            <?php Pjax::begin(['id' => 'grid-container']); ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        [
                            'attribute' => 'label',
                            'header' => 'Тип вывода денег'
                        ],
                        [
                            'attribute' => 'countries',
                            'header' => 'Показывать в странах'
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'header' => '',
                            'template' => '{update}',
                            'buttons' => [
                                'update' => function ($url, $model) {
                                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                        'title' => Yii::t('app', 'Update {0}', 'Wallet type'),
                                        'data-pjax' => 0,
                                        'class' => 'modal-edit'
                                    ]);
                                }
                            ],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                switch ($action) {
                                    case 'update':
                                        $url = Url::to(["/withdrawal-type/update", 'type' => $model['type']]);
                                        break;
                                }
                                return $url;
                            }
                        ],
                    ],
                ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>